# Generated by Django 3.1.2 on 2020-10-13 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coche',
            fields=[
                ('matricula', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('marca', models.CharField(choices=[('2', 'HYUNDAI'), ('0', 'CHEVROLET'), ('1', 'KIA'), ('3', 'MERCEDES'), ('4', 'OTRO')], max_length=1, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
                ('numero_de_puertas', models.CharField(max_length=50)),
                ('extras_instalados', models.CharField(max_length=50)),
                ('Codigo_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
            ],
        ),
    ]
