# Generated by Django 3.1.2 on 2020-10-13 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coches_vendidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coche',
            name='marca',
            field=models.CharField(choices=[('3', 'MERCEDES'), ('4', 'OTRO'), ('2', 'HYUNDAI'), ('0', 'CHEVROLET'), ('1', 'KIA')], max_length=1, verbose_name='Marca'),
        ),
    ]
