# Generated by Django 3.1.2 on 2020-10-14 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coches_vendidos', '0002_auto_20201013_1349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coche',
            old_name='Codigo_cliente',
            new_name='codigo_cliente',
        ),
        migrations.AlterField(
            model_name='coche',
            name='marca',
            field=models.CharField(choices=[('2', 'HYUNDAI'), ('0', 'CHEVROLET'), ('4', 'OTRO'), ('3', 'MERCEDES'), ('1', 'KIA')], max_length=1, verbose_name='Marca'),
        ),
    ]
