# Generated by Django 3.1.1 on 2020-10-15 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coches_vendidos', '0003_auto_20201013_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coche',
            name='marca',
            field=models.CharField(choices=[('4', 'OTRO'), ('3', 'MERCEDES'), ('0', 'CHEVROLET'), ('1', 'KIA'), ('2', 'HYUNDAI')], max_length=1, verbose_name='Marca'),
        ),
    ]
