# Generated by Django 3.1.1 on 2020-10-16 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coches_vendidos', '0005_auto_20201015_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coche',
            name='marca',
            field=models.CharField(choices=[('1', 'KIA'), ('4', 'OTRO'), ('3', 'MERCEDES'), ('0', 'CHEVROLET'), ('2', 'HYUNDAI')], max_length=1, verbose_name='Marca'),
        ),
    ]
