# Generated by Django 3.1.2 on 2020-10-13 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coches_vendidos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cambio_aceite', models.CharField(choices=[('0', 'SI'), ('1', 'NO')], max_length=1, verbose_name='Cambio aceite')),
                ('Cambio_filtro', models.CharField(choices=[('0', 'SI'), ('1', 'NO')], max_length=1, verbose_name='Cambio filtro')),
                ('revicion_frenos', models.CharField(choices=[('0', 'SI'), ('1', 'NO')], max_length=1, verbose_name='revicion frenos')),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coches_vendidos.coche')),
            ],
        ),
    ]
