# Generated by Django 3.1.2 on 2020-10-13 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revisiones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revision',
            name='Cambio_aceite',
            field=models.CharField(choices=[('1', 'NO'), ('0', 'SI')], max_length=1, verbose_name='Cambio aceite'),
        ),
        migrations.AlterField(
            model_name='revision',
            name='Cambio_filtro',
            field=models.CharField(choices=[('1', 'NO'), ('0', 'SI')], max_length=1, verbose_name='Cambio filtro'),
        ),
        migrations.AlterField(
            model_name='revision',
            name='revicion_frenos',
            field=models.CharField(choices=[('1', 'NO'), ('0', 'SI')], max_length=1, verbose_name='revicion frenos'),
        ),
    ]
