# Generated by Django 3.1.1 on 2020-10-16 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('revisiones', '0002_auto_20201013_1349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='revision',
            old_name='matricula',
            new_name='matricula_coche',
        ),
    ]
