# Generated by Django 3.1.1 on 2020-10-16 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revisiones', '0003_auto_20201015_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revision',
            name='Cambio_aceite',
            field=models.CharField(choices=[('0', 'SI'), ('1', 'NO')], max_length=1, verbose_name='Cambio aceite'),
        ),
        migrations.AlterField(
            model_name='revision',
            name='Cambio_filtro',
            field=models.CharField(choices=[('0', 'SI'), ('1', 'NO')], max_length=1, verbose_name='Cambio filtro'),
        ),
        migrations.AlterField(
            model_name='revision',
            name='revicion_frenos',
            field=models.CharField(choices=[('0', 'SI'), ('1', 'NO')], max_length=1, verbose_name='revicion frenos'),
        ),
    ]
